
---
title: "NJ and Parsimony Trees from Single-Copy Ortholog OG0009904"
output: html_document
---


```{r}
#load libraries
library(ape)
library(adegenet)
library(phangorn)

#path to alignment file
alignment_file <- "C:/Users/toddf/toddfphylo563/Data/Results_Mar04_1/Orthogroup_Sequences/OG0000000_aligned.fa"


#read aligned FASTA
alignment <- read.phyDat(alignment_file, format="fasta", type="AA")

#summary of alignment
print(alignment)

#number of sequences
cat("Number of sequences:", length(alignment), "\n")

#alignment length
cat("Alignment length:", attr(alignment, "nr"), "\n")

# Compute distance matrix
dist_matrix <- dist.ml(alignment)

#neighbor Joining tree
tree <- NJ(dist_matrix)

# tree
plot(tree, main="Neighbor Joining Tree")


```

## example tree

```{r}
#labeling sequence
tree$tip.label <- paste0("Seq_", seq_along(tree$tip.label))

set.seed(1)
subset_tips <- sample(tree$tip.label, 10)

subtree <- keep.tip(tree, subset_tips)

plot(subtree, use.edge.length = FALSE, cex = 0.9)


```
